### ISSUE TITLE
Why pify instead of util.promisify?

### ISSUE THREAD

**Issue by styfle** [sindresorhus/make-dir#10]
Since this is supposed to be a more modern version of `mkdirp`, why not remove the `pify` dependency and use [util.promisify](https://nodejs.org/api/util.html#util_util_promisify_original) that was added in [Node 8](https://www.ceriously.com/blog/post.php?id=2017-05-09-nodejs-promisify.md)?

Are you supporting older versions of Node?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/make-dir/blob/c1294d718f3d82fd238e91ccbda08c9b6ad474e0/package.json#L12-L14

I will move my packages to target Node.js 8 in April.

**Comment by styfle** [comment]
Perfect, thanks 👌
