### ISSUE TITLE
import * as makeDir doesn't work in 2.1.0

### ISSUE THREAD

**Issue by vitkarpov** [sindresorhus/make-dir#12]
Hey there! 👋 

Seems there's a problem with TypeScript typings in `2.1.0`:

This code doesn't compile:

```js
import * as makeDir from 'make-dir';

await makeDir(dir);
```

TypeScript says:

```
Cannot invoke an expression whose type lacks a call signature.
```

If to change import to `import makeDir from 'make-dir'` it works fine though 🤔

**Comment by vitkarpov** [comment]
If it was intentional then it'd be better to make a major release, right?

**Comment by sindresorhus** [comment]
Type definitions now ship with the package and might differ from the ones at DefinitelyTyped.

> If it was intentional then it'd be better to make a major release, right?

No. It's not a semver-breaking change to introduce types. It's the fault of TypeScript that it picks the typings from the package over the ones from DefinitelyTyped. See: https://github.com/Microsoft/TypeScript/issues/19283 I would encourage you to open a new TypeScript issue about this and refer to my issue.

**Comment by vitkarpov** [comment]
It's weird that [make-dir on DefinitelyTyped](https://www.npmjs.com/package/@types/make-dir) says "make-dir provides its own type definitions, so you do not need this installed" 🤔

**Comment by vitkarpov** [comment]
> It's the fault of TypeScript that it picks the typings from the package over the ones from DefinitelyTyped.

@sindresorhus I see the opposite case: typings are being picked from the package itself and *not* from `@types/make-dir`, from that point of view I don't see the problem.
But the typings in the package seem to be inaccurate, don't they?

**Comment by vitkarpov** [comment]
> It's not a semver-breaking change to introduce types.

I totally agree with that. If https://github.com/Microsoft/TypeScript/issues/19283 is not an issue indeed here there's a bug in `2.1.0` and a fix would be in `2.1.1`.

**Comment by sindresorhus** [comment]
> The typings in the package seem to be inaccurate, don't they?

No, it's a default export.

**Comment by vitkarpov** [comment]
Default export (`import makeDir from 'make-dir'`) works as expected, the problem is with `import * as makeDir from 'make-dir'`

**Comment by vitkarpov** [comment]
Nevemind, that's okay.
