### ISSUE TITLE
can't make dir on parent's parent folder

### ISSUE THREAD

**Issue by kakarlus** [sindresorhus/make-dir#17]
Hello,

I was just testing the File Manager Webpack Plugin (https://github.com/gregnb/filemanager-webpack-plugin) which uses this module and i found out that it's not possible to create a folder which is outside of the current dir.

```
makeDir('../../folder/subfolder/subfolder/');
```

Regards,
Carlos

**Comment by sindresorhus** [comment]
What Node.js version? What error do you get (include the full stack trace)?

**Comment by kakarlus** [comment]
my bad, i tested it by itself, it's working. i'll have to look at the webpack plugin now.
