### ISSUE TITLE
Stale process.umask() value

### ISSUE THREAD

**Issue by RyanZim** [sindresorhus/make-dir#18]
I'm working on https://github.com/jprichardson/node-fs-extra/issues/619; and experimenting with switching our current implementation (an internal fork of `mkdirp@0.x`) to an internal fork of `make-dir`. In testing against our existing test suite, I discovered what seems to be a bug, and thought I'd report it upstream here.

The default `mode` is based on `process.umask()`, which is set here:

https://github.com/sindresorhus/make-dir/blob/9de64744e3d86227a470054be47870f1b1da8ed1/index.js#L8

However, this is one static value, based on the `process.umask()` value at require-time. If the user sets the `umask` with  `process.umask(value)` after requiring `make-dir`, the new `umask` will not be respected.

Fix for this would be to fetch defaults in a function, called at runtime, to get a fresh `process.umask()` call for every method call. Happy to submit a PR if this is confirmed as a bug.

**Comment by sindresorhus** [comment]
Yup. That looks like a bug. A PR would be awesome :)
