### ISSUE TITLE
Inconsistency between async and sync implementations

### ISSUE THREAD

**Issue by RyanZim** [sindresorhus/make-dir#23]
In the sync implementation, we make a `statSync` call, and if it fails, the original `mkdirSync` error is thrown:

https://github.com/sindresorhus/make-dir/blob/9de64744e3d86227a470054be47870f1b1da8ed1/index.js#L137-L143

However, in the async implementation, we have no error handling for the `stat` call, and any failure there would bubble up:

https://github.com/sindresorhus/make-dir/blob/9de64744e3d86227a470054be47870f1b1da8ed1/index.js#L84-L87

In an earlier (pre-async/await) version, we properly swallowed any `stat` errors, and threw the original error, like the sync implementation:

https://github.com/sindresorhus/make-dir/blob/379001fd63b9a1037ad9d840b4ec0b0e40c69fbd/index.js#L76-L80

I don't have a test case to show if this actually creates an inconsistency for the end user, but it was just noticed in review, and I thought I'd report upstream.

**Comment by sindresorhus** [comment]
Good catch. That should indeed be fixed.
