### ISSUE TITLE
Add an empty option

### ISSUE THREAD

**Issue by zkochan** [sindresorhus/make-dir#29]
I need to make a directory and I need to always have it empty. It will almost never exist, so I don't want to run rimraf each time before making the directory. That's a redundant fs operation.

Instead, could makeDir have an empty option? If empty is true, then an exception is thrown here:

https://github.com/sindresorhus/make-dir/blob/6d029fe1f75f1a02fcdd7a67f34eadf0941a424f/index.js#L90-L93

Or alternatively, some option that doesn't silence the EEXIST exceptions. Like opts.throwOnExists

A third possible solution could be that makeDir returns something that tells us if the directory already existed. Like it could return `{ alreadyExisted: true }`

**Comment by papb** [comment]
Side note: [this can be done with `dir` in fs-jetpack](https://github.com/szwacz/fs-jetpack#dirpath-criteria)

**Comment by RyanZim** [comment]
Can also be done with `fs-extra` `emptyDir` https://github.com/jprichardson/node-fs-extra/blob/master/docs/emptyDir.md

**Comment by zkochan** [comment]
but it starts with readdir

https://github.com/jprichardson/node-fs-extra/blob/a2738d390694ae8dc32a8c27e76db08c9963e570/lib/empty/index.js#L11

In my case, it is an edge case that the target directory exists. So I'd prefer if it starts with the mkdir command and only removes the directory if an EEXIST exception is thrown.

**Comment by RyanZim** [comment]
Honestly, if you need to be that hyper-optimized, you're probably best off embedding the function in your own code; because there are many other use-cases where it would be more efficient to do the exact opposite. A library can't cover all cases with highest efficiency.

**Comment by zkochan** [comment]
I might do that. But make-dir almost does what I need. It runs mkdir without checking the existence of the directory first. So adding an `empty` option would not be a breaking change.

**Comment by zkochan** [comment]
I guess I will create a new package for this. This one is not that useful anymore, as NodeJS supports recursive mkdir natively
