### ISSUE TITLE
umask warnings

### ISSUE THREAD

**Issue by ql-nano** [sindresorhus/make-dir#31]
Hello. If your package really needs process.umask() without args (**deprecated**), then you may use [**get-umask**](https://www.npmjs.com/package/get-umask)  module. It suppresses those annoying warnings. And yeah, it's written by me.
If you would like to get any help, I'll make pull request tomorrow.

**Comment by sindresorhus** [comment]
This was already fixed in https://github.com/sindresorhus/make-dir/commit/b5a98efbe37afa91b02c3a62cb0ad0c14f03cc87.
