### ISSUE TITLE
Add option to disable absolute path resolution (useful for alternate fs)

### ISSUE THREAD

**Issue by DeltaF1** [sindresorhus/make-dir#33]
https://github.com/RangerMauve/dat-fetch uses make-dir to write to a separate filesystem by passing in the fs object. The calls to `path.resolve` however still operate in the context of the filesystem that nodejs is running in and so prepends the current working directory to some paths. These paths are not valid in the context of the separate filesystem being operated upon by make-dir and so there are unwanted intermediate folders being created. (see [this issue if interested](https://github.com/AgregoreWeb/agregore-browser/issues/88)).

If I made a PR to add a no-resolve option is it possible that this would be merged or should I just fork the package?

**Comment by sindresorhus** [comment]
Would a `cwd` (current working directory) option solve your problem?
