### ISSUE TITLE
Try Catch problems

### ISSUE THREAD

**Issue by jiveturkeyJay** [sindresorhus/make-dir#35]
Some of the code in this is preventing installation

`client/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^
`

There are a number of try catch statements that don't have any parenthesis.
I'm not sure if try catches are allowed without parenthesis but in this case it is not work.
I've tried a few fixes that have been suggested such as updating node version, updating the version of the packages that are installing make-dir but no good.

Thanks

Jason

**Comment by RyanZim** [comment]
If you're using a new enough Node version, it should work fine. Can you post the full error with stack trace?

**Comment by sindresorhus** [comment]
Upgrade your Node.js version.
