### ISSUE TITLE
Semver dependency in published package does not match what's in the repo

### ISSUE THREAD

**Issue by jpage-godaddy** [sindresorhus/make-dir#39]
I have `make-dir@3.1.0` installed. Its `package.json` contains this dependency:

```
"semver": "^6.0.0"
```

...yet [in the `main` branch](https://github.com/sindresorhus/make-dir/blob/main/package.json#L43), the version is set to:

```
"semver": "^7.3.2"
```

Was there perhaps a missed publish of this change? It appears that the `semver` version bump will resolve a security audit failure, but the published package is still on `^6.0.0`, so the issue cannot be resolved at present.

**Comment by RyanZim** [comment]
This change was not published as per https://github.com/sindresorhus/make-dir/pull/32#issuecomment-722572505.  make-dir itself should be unaffected by the [semver security issue](https://security.snyk.io/package/npm/semver/6.3.0), but the noisy audit failure might warrant the publication of a new version; @sindresorhus?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/make-dir/releases/tag/v4.0.0
