### ISSUE TITLE
NPM package.json not updated

### ISSUE THREAD

**Issue by enricoromeo** [sindresorhus/make-dir#40]
It seems the semver dependency on the package.json from npm is ver 6.0.0 (moderate severity vulnerability) instead of 7.3.2
"dependencies": {
		"semver": "^6.0.0"
	},

The correct version should be this one (from GitHub):
	"dependencies": {
		"semver": "^7.3.2"
	},

**Comment by sindresorhus** [comment]
Duplicate of #39
