### ISSUE TITLE
3.x release supporting recent semver?

### ISSUE THREAD

**Issue by PeterJCLaw** [sindresorhus/make-dir#43]
I realise that with v4 now being released the 3.x series is no longer the latest, however a number of users are still stuck on the 3.x series due to the Node version requirement. (For my use-case the chain is: `cspell` 6.x -> `configstore` 5.x -> `make-dir` 3.x; each package along the chain has its own reasons for not picking up a major version bump of the dependent package; https://github.com/streetsidesoftware/cspell/issues/4594, https://github.com/yeoman/configstore/issues/89).

As far as I can tell the 6.x to 7.x version bump of `semver` isn't breaking to the usages in `make-dir`, so I'm expecting that cherry-picking https://github.com/sindresorhus/make-dir/pull/32/commits/777eed34cff6ac916372c95b08ba8d808acb25f9 then releasing a 3.x would suffice. Would you be up for doing that? (I'd be happy to create a PR if that's useful, though given the size of the change I'm assuming it's not particularly so)

**Comment by sindresorhus** [comment]
The `semver` vulnerability does not apply to `make-dir` as it does not use `semver` with untrusted user-input. I understand you want the vulnerability gone from `npm audit`, but I don't want to waste all my maintainer time on bumping dependencies for "vulnerabilities" that in reality affect no one.

https://overreacted.io/npm-audit-broken-by-design/
